baseURL = "https://nooonde.github.io/hugo/"
languageCode = "de-de"
title = "My Starter Template"
publishDir = "docs"
theme = "suedsicht"

[mediaTypes]
[mediaTypes."text/htaccess"]
suffix = "htaccess"

[outputFormats]
[outputFormats.MyHTA]
mediaType = "text/htaccess"
baseName = ""
isPlainText = true

[outputs]
  home = ["HTML", "MyHTA"]
  page = ["HTML", "MyHTA"]

[params]
  description = "My Starter Template"
  author = "Daniel"
  keywords = "keyword1, keyword2, keyword3"

[[menu.main]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -90
    url = "/about/"
    identifier = "about"
[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/getting-started/"
    identifier = "started"
[[menu.main]]
    name = "under getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/getting-started/"
    identifier = "under-started"
    parent = "started"
[[menu.main]]
    name = "under the blog"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/getting-started/"
    identifier = "undertheblog"
    parent = "blog"
